version: '3.8'

services:
  # Основное приложение ROCKET PC (простая версия)
  app:
    build: .
    container_name: rocket-pc-app
    ports:
      - "8000:8000"
    environment:
      # Переменные окружения из .env файла
      - DATABASE_URL=${DATABASE_URL}
      - APP_TITLE=${APP_TITLE}
      - APP_DESCRIPTION=${APP_DESCRIPTION}
      - APP_VERSION=${APP_VERSION}
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
      - TIMEZONE=${TIMEZONE}
    volumes:
      # Монтируем только папку uploads для сохранения загрузок
      - uploads_data:/app/static/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads_data:
    driver: local

networks:
  default:
    name: rocket-pc-network